### ISSUE TITLE
file unit of measure inch->mm

### ISSUE THREAD

**Issue by BenRoe** [wizarddata/Ergodash-Case#1]
Hi,
i imported the stl files in slic3r/cura and the model is tiny (wrong scale).
https://www.reddit.com/r/3Dprinting/comments/9e5c6i/does_anyone_know_why_when_i_design_something_in/
This is because you exported the model in inch.
Change unit of measure to mm before you export it.
If you not agree, people must scale the model 2540%

**Comment by wizarddata** [comment]
Models have been uploaded in mm, thanks.
