### ISSUE TITLE
Provide STEP or similar source files

### ISSUE THREAD

**Issue by coredump** [wizarddata/Ergodash-Case#3]
Hello!

It would be nice to have the source files in an editable format (STEP for example). It would make it easier to make modifications.

**Comment by Kirinkun** [comment]
+1
It'd be really great to make minor modifications to the files so I can e.g. Adapt the legs to my preferences :)

**Comment by Kirinkun** [comment]
@coredump After talking to wizarddata on reddit (took me a while to write a message), he was kind enough to provide a link to the fusion360 design :)

https://a360.co/2LRTRW4

**Comment by wizarddata** [comment]
Link to fusion360 model has been added to the readme as well.
